# Generated by Django 5.1.1 on 2024-09-11 08:53

import commonapp.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0001_initial'),
        ('saloon', '0001_initial'),
        ('saloonfinance', '0001_initial'),
        ('saloonservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Price')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount in default currency')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Current stock')),
                ('currency', models.ForeignKey(default=commonapp.models.Currency.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='commonapp.currency', verbose_name='Currency')),
                ('item_purpose', models.ManyToManyField(related_name='items', to='saloonservices.hairstyle', verbose_name='Item purpose')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('name', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('purchase_price_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price in default currency')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase date')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Supplier')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='saloonfinance.cashregister', verbose_name='Cash Register')),
                ('currency', models.ForeignKey(default=commonapp.models.Currency.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='commonapp.currency', verbose_name='Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='salooninventory.item', verbose_name='Item')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Item Purchase',
                'verbose_name_plural': 'Item Purchases',
            },
        ),
        migrations.CreateModel(
            name='ItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saloon.barber', verbose_name='Barber')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salooninventory.item', verbose_name='Item')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='saloon.salon', verbose_name='Salon')),
                ('shave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_used', to='saloonservices.shave', verbose_name='Shave')),
            ],
            options={
                'verbose_name': 'Item Used',
                'verbose_name_plural': 'Items Used',
                'unique_together': {('item', 'shave', 'salon')},
            },
        ),
    ]
