# Generated by Django 5.1.1 on 2024-09-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='can_manage_barbers',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='can_manage_finance',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='can_manage_hairstyle',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='can_manage_inventory',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='can_manage_shave',
        ),
    ]
