# Generated by Django 5.1.1 on 2024-09-11 08:53

import commonapp.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0001_initial'),
        ('saloon', '0001_initial'),
        ('saloonfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('current_tariff', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Current Tariff')),
                ('currency', models.ForeignKey(default=commonapp.models.Currency.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='commonapp.currency', verbose_name='Currency')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Hairstyle',
                'verbose_name_plural': 'Hairstyles',
                'unique_together': {('name', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='HairstyleTariffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Tariff')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective Date')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_history', to='saloonservices.hairstyle', verbose_name='Hairstyle')),
            ],
            options={
                'verbose_name': 'Hairstyle Tariff History',
                'verbose_name_plural': 'Hairstyle Tariff Histories',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Shave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Amount in default currency')),
                ('date_shave', models.DateField(default=django.utils.timezone.now, verbose_name='Shave date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaves', to='saloon.barber', verbose_name='Barber')),
                ('cashregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaves', to='saloonfinance.cashregister', verbose_name='Cash Register')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shaves', to='saloon.client', verbose_name='Client')),
                ('currency', models.ForeignKey(default=commonapp.models.Currency.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shaves', to='commonapp.currency', verbose_name='Currency')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaves', to='saloonservices.hairstyle', verbose_name='Hairstyle')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaves', to='saloon.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Shave',
                'verbose_name_plural': 'Shaves',
            },
        ),
    ]
